import React from 'react'
import Form from '@/app/_components/checkout/Form'
import Summary from '@/app/_components/checkout/Summary'

export const metadata = {
  title: 'Checkout',
  // description: 'Generated by create next app',
}

export default function Checkout() {
  return (
    <div>
        
    <Form/>
    {/* <Summary/> */}

    </div>
  )
}
