"use client"
import './globals.css'
import Header from './_components/shared/Header'
import Footer from './_components/shared/Footer'
import { store } from './_redux/store'
import { ReduxProvider } from './_redux/provider'
import About from './_components/shared/About'
import Menu from './_components/menu/Menu'


export const metadata = {
  title: 'Audiophile',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className="font-display">
     
        <ReduxProvider>
        <Header />
       
          {children}
        
        <About/>
        <Footer/> 
        </ReduxProvider>

      </body>
    </html>
   
  )
}
